version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
      POSTGRES_DB: crypt_echo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: ./docker         # This will use the Dockerfile in the docker/ folder
    container_name: python_app_container
    ports:
      - "8000:8000"          # Exposing port 8000 for the app (or change as needed)
    volumes:
      - .:/app               # Mounts the current directory to /app in the container
    
    
volumes:
  pgdata:
